# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3dfe518789b283cc310e07b72945eb6e455197a02dfb1ab311202d8aaf928c5e7b2111d677f128e3727e4260bae2862df13ca79a050f687cb1e75e5a3e0c866

test:
  secret_key_base: 70e686ae83b30dc47918c4b70ae0ad3e1ce9ab1e5dd8d131e011af527ee525622641ed87422022e5989f75d34c92ee94e4749c54f846ecbac5082af7faac18b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
